### ISSUE TITLE
Account information isn't populated by ID Token?

### ISSUE THREAD

**Issue by whytheplatypus** [TransparentHealth/sharemyhealth#12]
On logging in with with an Open ID provider my account's email, last name, and phone number are blank (at least email and last name should be present in the ID Token).

**Comment by whytheplatypus** [comment]
reference for social auth pipline https://python-social-auth-docs.readthedocs.io/en/latest/pipeline.html

**Comment by aviars** [comment]
This was resolved some time ago.
