### ISSUE TITLE
Clickable Mockup Review

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/sharemyhealth#14]
Clickable mockup review:

https://xd.adobe.com/view/38a1bc46-ef1d-4236-5539-d4510f012599-4e90/

**Comment by aviars** [comment]
Overall
-------

I think the layout approximates what we will envision, but I think the user icon in the left needs to have an image and content. It loks like the items on  the right are personal settings, while the items on the left are of another user.  The mockup should clearly delineate changing a self settings versus for another. In the current mockup you have yourself in there 2x which I think will confuse people.

Specific Changes
------------------

* Change`Organizational Agents` to `Identifiers`
* Change `Organization Settings` to `Organizations`
* Remove the email icon
* `Re-verify Email` is off center
* Remove additional North Carolina References

**Comment by apwalker22** [comment]
Revised Version:
https://xd.adobe.com/view/38a1bc46-ef1d-4236-5539-d4510f012599-4e90/?fullscreen

**Comment by aviars** [comment]
Hi @apwalker22  Thanks for the updates. I'll share.

**Comment by aviars** [comment]
Adding some other thoughts with @LeaBalloni .  

* We need a landing page which includes search.
* Move vertical nav into a separate settings screen.
* Move content on right to 
* The desktop browser experience should resemble GitHub.
* We need a mobile too. Have a bottom nav for mobile (like Instagram an many other apps). 
* The login page should have the login more prominent.

* Notes is a function of Organizations.  Show one organization with an Note button. Show the other organization without. They are without because the logged in user is not a member of the organization.

**Comment by aviars** [comment]
More notes @apwalker22 
[notes-on-mockup.pdf](https://github.com/TransparentHealth/sharemyhealth/files/2749637/notes-on-mockup.pdf)
