### ISSUE TITLE
SMH - API Endpoint Integration

### ISSUE THREAD

**Issue by ekivemark** [TransparentHealth/sharemyhealth#15]
# SMH - API Endpoint Integration
ShareMy.Health (SMH) is a Health Data Aggregation Platform.

This document outlines the capabilities that SMH requires in order to enable an account holder (consumer) to connect their account with one or more data platforms that SMH is authorized to integrate with.

## Functional Requirements

	- API Endpoint Connection Table (Server connections)
	- API Endpoint Resource Table  (Server API Resource Endpoints and consumer identifier filtering definition)
	- Consumer Crosswalk (Document Linkages to API Endpoints for consumer)
	- Crosswalk Identifier registration (Registering  consumer’s remote Identifier at an API Endpoint) 

These functional requirements will be defined based upon the FHIR specification and use of the FHIR REST API  as an API Endpoint that is used to access Patient-related records. ie. A consumer can only access their own records, or supporting reference records (eg. Practitioner, Organization, Medication records).

### API Endpoint Connection Table
An admin-only table is required that contains information about each registered API Endpoint.

Field | Type | Purpose 
----- | ----- | -----
Endpoint Name | string  | Friendly Name 
Active | Boolean | Switch to activate / Deactivate Endpoint 
|URL | URi |  URL of Endpoint 
ConnectionType |  Code | [Open, PrivateKey, UserAccount, ServerOAuth, UserOAuth ] 
KeyResource | string | Key Resource to link to eg. Patient - must have matching entry in Endpoint Resource Table 
ConnectionCredentialsDoc |  JSON | JSON dictionary holding connection credentials 
Organization | Link | Link to Organization Table 
Tag | string | comma delimited or list of tags to categorize API Endpoint type 

This table may need to link to a table that maintains the OAuth Access and Refresh Tokens where OAuth is used.
 
### API Endpoint Resource Table
An Admin-only table is required to define the Endpoint resources available via each API Endpoint connection.

Field | Type | Purpose
----- | ----- | -----
ResourceName | string | Friendly Resource Name (not unique) 
ResourcePath | URI string | path definition to resource relative to API Endpoint BaseURL 
API Endpoint | Link | Link to API Endpoint connection table
Protected | boolean | Switch to indicate if resource is protected. e.g. False for Organization Resource and other reference resources 
Description | string |. Friendly description of resource
UserFilter | boolean | Switch to indicate endpoint should apply query parameter to restrict content to the connecting consumer
FilterType | Code | Indicate filtering is appended to path or applied as query parameter [Path, Query] 
FilterString | String | Syntax with replaceable parameters used to apply filtering. eg. "patient=Patient/12345" might be represented as "patient=Patient/{{Target_User_Id}}" 
QueryExclusions | String/List | list of query parameters to block from inbound query
QueryInclusions | String/List | list of query parameters to add to inbound query
MatchingParameter | JSON | Query Parameters to submit to match patient eg. System and Value for SSN

### Consumer Crosswalk

An Admin Only Table that maintains the list of connections between an SMH user and one or more backend API Endpoints.

Field | Type | Purpose
----- | ----- | -----
User | UserRef | User Account on SMH 
API Endpoint | Link | Link to API Endpoint Connection
API Endpoint Resource | Link | Link to API Endpoint Resource 
TargetId | String | Target ID for Patient record
ConnectTime | DateTime | Date/Time first connected  LastConnected | DataTime | Date/Time of latest connection

### Consumer Identification Registration

When a SMH Consumer connects to a back-end API Endpoint there are two likely scenarios for the Consumer Matching process.

1. The connection is via a user-oriented OAuth authorization. In this scenario the API endpoint should be returning data that is specific to that consumer.  In that scenario there would be no need to apply filters to the data that is requested because the back-end API platform would be applying the filtering itself.  This would be the scenario if we connected to the Blue Button 2.0 API at CMS.

2. The connection is via a server-level access control. In this case SMH may be able to access any records when calling the API Endpoint. In this scenario the resource calls would be performed with additional parameters to limit data returned to only the SMH Consumer. 

In the latter scenario a patient matching step is required. In this case a search would be made to the key resource at the API Endpoint, e.g. The Patient resource and the MatchingParameter string would be applied, after substituting any replaceable parameters.  If the search request returns a single record. e.g. after a match on SSN., or a series of replaceable parameters (Name, DOB, Gender) the ID of the returned record would be added to the Crosswalk. This would then be used as a replaceable parameter in subsequent calls to resources at that API Endpoint that required filtering using Patient ID.

In the event that a unique search result is not returned it will be necessary to report a failed unique match. The result should then be posted to a queue where a CBO Administrator could obtain more data in order to make a unique match. This may require the Administrator to. Manually update the Crosswalk record with the resolved unique Patient ID.

## Onboarding an API Endpoint
The process for Onboarding a new API Endpoint is as follows:

- Add a record to the API Endpoint Connection Table
- Identify the Prime Resource (e.g. Patient) and update the API Endpoint Connection Table
- Retrieve the OpenAPI Definition Document or FHIR Capability Statement
- Register each unique API Endpoint in the API Endpoint Resource Table
- Build the MatchingParameter syntax needed to perform a patient matching search
- Add the FilterString with replaceable parameters needed to retrieve a single patient record
- Add any additional QueryInclusion and QueryExclusion Parameters that are required
- Test the Patient Matching and Patient Request requests
- Test the retrieval of data for each API Resource endpoint.

**Comment by aviars** [comment]
@ekivemark I was able to most of what you have here with only a Crosswalk table. See PR #26
