### ISSUE TITLE
Remove `userprofile-test` route

### ISSUE THREAD

**Issue by whytheplatypus** [TransparentHealth/sharemyhealth#21]
remove test route for oidc test route

https://github.com/TransparentHealth/sharemyhealth/blob/master/apps/accounts/views/user_profile.py#L40-L61

https://github.com/TransparentHealth/sharemyhealth/blob/master/apps/accounts/urls.py#L9

**Comment by aviars** [comment]
I think yes eventually, but having this for now is useful in development.
