### ISSUE TITLE
Update example `CDA` endpoint with DRF and multiple Renderers

### ISSUE THREAD

**Issue by whytheplatypus** [TransparentHealth/sharemyhealth#22]
should result in the ability to request the resource as `application/fhir+json` `application/json` or `application/xml`

https://github.com/TransparentHealth/sharemyhealth/blob/master/apps/api/urls.py#L9-L10

https://github.com/TransparentHealth/sharemyhealth/blob/master/apps/api/views.py#L7-L18

**Comment by aviars** [comment]
@whytheplatypus This really won't be needed as I just made this as a sample/mockup.  I think our plan to to support FHIR and find a way to convert CDA into FHIR

**Comment by aviars** [comment]
Closing. We asren't officially supporting a CDA API.  We can revisit if it is requested by one or more stakeholders.
