### ISSUE TITLE
Allow CDA fetch only when user is present.

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/sharemyhealth#77]
When fetching data from the HIE, allow updates when the user is present.  For the purposes of this change request,  "present" means an authenticated user (e.g. a relying party's session established by Open ID Connect). The user is there performing/pushing the refresh button.  Refresh does not occur when OAuth2 token request is made.

User (Member/Patient) shall re-attest to the HIE user agreement in order to update data.

(We need confirmation/revision of the desired behavior.)

**Comment by aviars** [comment]
I think this is done form PR #83 @seanharrison .  Whats the best way to test this?

**Comment by sharrisoncaktus** [comment]
A couple of differences between this and #83:
* There is no re-attestation in the "refresh data" workflow.
* The request being made to sharemyhealth is via token auth, and IIRC there's no way to tell whether the requesting user is the member or an approved org agent (you and I talked about this at the time).

**Comment by sharrisoncaktus** [comment]
The way I tested it was to open a `./manage.py dbshell` and `update ... set updated_at = more_than_ a_day_ago` so that the "refresh" button would appear. (Can't do it in python shell, the auto_update_now=True blocks it.)

**Comment by aviars** [comment]
Okay if this does not suffice we will just make smh tokens have a very short lifespan. Closing for now.
